export const ERROR_CODES = {
  NOT_EXIST: 'ERROR_CODE_NOT_EXIST',
  INVALID_TYPE: 'ERROR_CODE_INVALID_TYPE',
  MISSING_VALUE: 'ERROR_CODE_MISSING_VALUE',
  INTERNAL_SERVER_ERROR: 'ERROR_CODE_INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'ERROR_CODE_UNAUTHORIZED',
  INVALID_VALUE: 'ERROR_CODE_INVALID_VALUE'
}
